name: Fetch Data

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install node-fetch

      - name: Execute JavaScript action
        run: node fetchData.js

      - name: Upload JSON artifact
        uses: actions/upload-artifact@v2
        with:
          name: result
          path: result.json
